### ISSUE TITLE
Remove an old unused code

### ISSUE THREAD

**Issue by IsaacMorris1980** [colinkiama/UWP-App-Launcher#134]
Need to clean up the code base to make the application not so big containing orphanded code

**Comment by mediaexplorer74** [comment]
> orphanded code

Oh... orphaned code? Are you planned to remove "15063" compatibility? So, "good-bye, Windows 10 Mobile... Sleep well" .
Did you have some Lumia phone at 2023 year? I still using L950 =) But I don't have enough tech. skills to install some "foreign shell" (non-UWP) directly into the operating system.... Only great hackers (such Fadil Fadz, Empyreal96, etc.) have "silent knowledge"  how to inject special apps into "obsolete" W10M, IMHO...

I hope that you leave "old_version" branch ontouched (for sweet new future when some genius on Earth planet researched new methods to install system apps in Win10Mobile 15254..))

Best,
MediaExplorer

**Comment by IsaacMorris1980** [comment]
@mediaexplorer74  the latest builds dropped  15063 i created 16299 sdk and the user on #61 was able to use it on 15254.

If it does not work i can open a different branch and continue or split of PC into a different repo.  I do not plan moving past 16299 since that is the last sdk that should support windows mobile 15254 build.  

If it does not work i can create a special branch but it might not have all current features

**Comment by mediaexplorer74** [comment]
> @mediaexplorer74 the latest builds dropped 15063 i created 16299 sdk and the user on #61 was able to use it on 15254.

16299 sdk needs .net standard 2.0 libraries.
It's wonderful news that the user on #61 was able to use it on 15254 ( .net standard 1.4 compatibility only). Ok, I'll try to check this magic info... ;)

> If it does not work i can create a special branch but it might not have all current features

Great. Good plan. Thank you very much! Good luck on future appLauncher building(s). I love your cool "Fresh-looking system shell" =))

P.S. 16299 has Polaris "codename"... 
About/over 3 year(s) I cannot find any W10M Polaris ffu .... with normal .net standard 2.0 support for modern coding :)

**Comment by IsaacMorris1980** [comment]
@mediaexplorer74   do the latest builds work on your device?

**Comment by mediaexplorer74** [comment]
> @mediaexplorer74 do the latest builds work on your device?

No. If I try to deploy latest builds untouched (targeted to 16299 sdk) directly to my winphone, I catch epic fail. 
And I did not try to checking the code compatibility after 16299->15063 yet, sorry...

**Comment by IsaacMorris1980** [comment]
how long before it crashes immeditately or just before the main page displays?

**Comment by mediaexplorer74** [comment]
> how long before it crashes immeditately or just before the main page displays?

Can't answer. 
I can't even deploy compiled .appx file via Portal (if 16299 SDK used for appx building)

**Comment by IsaacMorris1980** [comment]
ok removing appcenter an a few other controls and rebasing back to 15063 to have same features but no analytics and crash reporting which i had disabled by default so no loss there as no one enabled it anyway

**Comment by IsaacMorris1980** [comment]
working on this along with #97
