### ISSUE TITLE
Improve loading time

### ISSUE THREAD

**Issue by IsaacMorris1980** [colinkiama/UWP-App-Launcher#158]
Need to lower launch of app to home screen time.

#134   might actually help with this but front end needs redesigned to have fewer items to load  then display items as needed

**Comment by mediaexplorer74** [comment]
> Need to lower launch of app to home screen time

Yea. What does the app on launch process, indeed? Scans some app packages, etc.? IMHO, the cache (file or database) needed. And button "Rescan app packages" at Settings page .

At my old poor winphone app starts up about 1 min /
However, i used old-version of appLauncher... Maybe, current version (master branch) helped me?... =) Ok, I 'll try the fresh codebase and repeat start time controlling (launch time counting?) (step 1: my notebook; step 2 - my mobile device if I could to downgrade src code to 15063 sdk)

**Comment by IsaacMorris1980** [comment]
@mediaexplorer74  i am thinking about marking it a preload app when you log it it preloads athe app and resumes app when you select it to open.
I am working on getting oldversion branch back to 15063.
Depending on the version the new versions load global app settings,sets up and disables appcenter analytics and crashes, i then scans the computer for uwp apps( i have a bug where it is finding some win32 apps) . as the main page loads it checks and if available loads background images, during loading main page it also calculates how many tiles can display and displays which page was selected(when the app closes naturally should be restored to that page when relaunched.)  I believe there is  a bug here.

**Comment by IsaacMorris1980** [comment]
@mediaexplorer74   i reverted oldversion to 15063

**Comment by IsaacMorris1980** [comment]
will check on loading time in newest build leaving open

**Comment by IsaacMorris1980** [comment]
Implemented in version 2.2.4
