### ISSUE TITLE
Can this Nice App auto-load after Device Reboot and change OS UI?

### ISSUE THREAD

**Issue by mediaexplorer74** [colinkiama/UWP-App-Launcher#168]
Hello / how are you?
One big dev question :  Can this great app autolaunch after device reboot?
In 2023, I wanted to try to install your great modern launcher into my old sweet Nokia/MS Lumia 950 :)
Maybe you know some secret method of W10M registry patching or something else?... ^ ^
Best,
MediaExplorer

**Comment by IsaacMorris1980** [comment]
@mediaexplorer74   are you meaning replace the start menu of the phone? or do you mean when the phone starts up it starts this app?

**Comment by mediaexplorer74** [comment]
> @mediaexplorer74 are you meaning replace the start menu of the phone? or do you mean when the phone starts up it starts this app?

Both. I mean "start menu/screen substitution" (system UI change view) and "app auto-starting" (auto-launching or auto-loading?) when windows 10 mobile starts up.

**Comment by IsaacMorris1980** [comment]
the second should be possbile not sure about the registry as i dont have a mobile registry to look at registry values to overwrite since if a bad value is input you might break the os requiring a full re-install(have had this happen to me on pc)

**Comment by IsaacMorris1980** [comment]
i will have to fix old version branch i just looked into that branch and it shows incorrect min/max values

**Comment by mediaexplorer74** [comment]
> the second should be possbile not sure about the registry as i dont have a mobile registry to look at registry values to overwrite since if a bad value is input you might break the os requiring a full re-install(have had this happen to me on pc)

ok. thank you for quick reply. I have Lumia phone. So, I'll try to "connect" (on)to the L950's registry (for autorun key exploration/exploring) via some hacker tool (i forgot the name of Gus33000's registry editor// so confused!)

**Comment by mediaexplorer74** [comment]
> i will have to fix old version branch i just looked into that branch and it shows incorrect min/max values

Hah , you discovered (noticed) my fork of your old-version branch? =) Great! Thank you very much for improving old sweet cancelled OS (windows 10 mobile). I'm dreaming on some cool alternative "shell" (launcher) for it =)

cheers up,
m.e.

P.S. Oh, I noticed that cool e-junk "dev family" (Empy96, Fadil, Basharast, etc.) created Win10-like "shell" for Lumias. But no source-codes at Github. That project called UniversalShell (fork of ADeltaX/MobileShell... idk). 
Please "ping" me if you find the src code first ;)

_pic: universal shell main screen view_
![image](https://user-images.githubusercontent.com/12032735/236742904-acd229a9-58a4-4e67-acba-c467b3395945.png)

**Comment by IsaacMorris1980** [comment]
can do.  The old version branch i though still supported 15063 but was supporting 16299, github informed me of the fork

**Comment by IsaacMorris1980** [comment]
@mediaexplorer74 new UI is waiting on a fix for color picking in settings then it will be rebased fully on 15063

**Comment by mediaexplorer74** [comment]
> @mediaexplorer74 new UI is waiting on a fix for color picking in settings then it will be rebased fully on 15063

Great / Super (in Rus.) !
P.S. I found&downloaded UniversalShell.appx, and started reverse-engeneering this mobile shell :) I discovered some interesting "native methods" to interop Virtual Screens, TaskBar, etc. 

My R.E.-sult (the code parts that idk how to reconstrunct I labaled by RnD "tag"):
[UniversalShell.zip](https://github.com/IsaacMorris1980/appLauncher/files/11471254/UniversalShell.zip)

 + the original (I noticed that the package compiled only for ARM and can't deployed onto PC):
 
[UniversalShell_1.0.88.0_ARM.zip](https://github.com/IsaacMorris1980/appLauncher/files/11471259/UniversalShell_1.0.88.0_ARM.zip)

+ small description that i found:
"UniversalShell (DEBUG_ARM_TEST)

This is nowhere near release worthy yet, no ETA for completion either. This is only for user testing and feedback

Requirements:
- Windows 10 Mobile 15063 and above

Current progress notes:
- Start Menu with search
- Multiple desktops
- Control Center with buttons (some just link to Windows Settings due to lack of UWP APIs for hardware)
- Pinnable icons, resizable and customizable
- Taskbar colour settings
- Widgets pane, user selectable in App Settings
- User selectable wallpaper (files or bing)

Known issues:
- Resetting the first icon/tile causes grid layout to glitch out.
- Modifying the displayed widgets sometimes doesn't apply if you close the settings window too quickly.
- Resetting app data in-app causes an exception of first load, reopening after this will fix this.
- maybe some more issues to be found.

Currently this cannot replace the stock Windows Mobile shell (starthost), research is still taking place with this"

Best wishes,
m.e.

**Comment by IsaacMorris1980** [comment]
will attempt this while working on #50  but will work on #50 first and only add this if quick and easy to implement or will implement in later build

**Comment by IsaacMorris1980** [comment]
initial implementation loads the app in the background if cpu and memory are available in version 2.2.4

**Comment by IsaacMorris1980** [comment]
@mediaexplorer74   will still look on how to override windows start menu
