### ISSUE TITLE
Drop Mobile support

### ISSUE THREAD

**Issue by IsaacMorris1980** [colinkiama/UWP-App-Launcher#31]
Should we drop support for phones as phones coming with or upgrading to windows 10 come less and less I am wondering if we should drop support for phones and continue to support tablets and other devices?  Any feedback would be appreciated.

**Comment by hooddy** [comment]
Is there a way to replays system Start screen on mobile with UWP launcher? As well as rearrange icons.

**Comment by hooddy** [comment]
Anyway to me its okay to drop mobile support.

**Comment by IsaacMorris1980** [comment]
@hooddy re-arranging icons is currently in the pre-release branch.  There may be a way to replace the start screen with app launcher but i dont have a mobile device to test with.   I am either going to drop mobile suppport or split the project phone/everything else.

**Comment by IsaacMorris1980** [comment]
i will be slitting the project as follows phones(minimum supported will be what the project is currently set at)  everything else will be set to 15063  to allow version adaptive xaml  this is to allow xaml to display control x if you have a version that has api y  or display fallback control if you do not have api

**Comment by BaRRaKudaRain** [comment]
Sorry for late answer, but you shouldn't drop mobile support. I wish you could continue support mobile version because default start screen on W10M seems ugly. Your launcher is the best app ever built for mobile platform. I wish I could give you my Lumia 950.

**Comment by IsaacMorris1980** [comment]
@BaRRaKudaRain   i had decided not to drop mobile support i am looking at splitting it into a project for Phones (redesigned at least via code made just for phones) and one project for everything else  (so i can use controls and other coding tricks to make it run faster and more stable)  I was also thinking about making minimum supported 15063 but dont know what version most people have on mobile
