### ISSUE TITLE
App is not installing due certificate issue

### ISSUE THREAD

**Issue by BaRRaKudaRain** [colinkiama/UWP-App-Launcher#32]
Hello! I've downloaded latest release of the app, but there a certificate issue. Certificate is outdated. Please re-create a package with a valid certificate.

**Comment by IsaacMorris1980** [comment]
Have a new build created just having internet problems that should be resolved by tomorrow

**Comment by BaRRaKudaRain** [comment]
Can you release it?

**Comment by IsaacMorris1980** [comment]
@BaRRaKudaRain   Released new version(1.2.5 i acccidentallly put in the incorrect version numbers) I  will leave this ticket open until you confirm it allows you to install

**Comment by BaRRaKudaRain** [comment]
Installed. All works. No more certificate issue. Thank you!
