### ISSUE TITLE
Poor tile colors

### ISSUE THREAD

**Issue by Ziggizag** [colinkiama/UWP-App-Launcher#45]
One image is worth more than thousand words:
![image](https://user-images.githubusercontent.com/2280036/69179079-34680700-0b0b-11ea-978e-c1a925c6a686.png)

**Comment by IsaacMorris1980** [comment]
@Ziggizag  i agree  i was trying to make them transparent so they would not block a lot of the background image at which point  i was unable to see the light colored icons.  I thought i had uploaded the change to put them blue again but  i did not they should be in my next release.  After looking at this picture i may create a build with nothing but the tile color change.   I am thinking about making the tile background color be configurable along with the opactity(how see through the tiles will be).   Would that be a good feature to have?

**Comment by Ziggizag** [comment]
Well,

I would say, the optimal solution would be giving the end user possibility to alter both: color and transparency of the tile background and color of the text descriptions.

But if we talk about transparency - I mean tile background only rather than entire tile. I am not aware is that feasible due to system limitation. In case the system does not allow having fully opaque tile icon and text on semi-transparent tile background - drop transparency completely as confusing.

And thank you for your prompt feedback, Isaac!

**Comment by IsaacMorris1980** [comment]
@Ziggizag   I will open a new issues and see about adding them to the planned accessibility build possibly will have to be with the localization build

**Comment by IsaacMorris1980** [comment]
@Ziggizag   the next release should have color and opacity configurability

**Comment by IsaacMorris1980** [comment]
@Ziggizag  Just released 1.5.6.0  which allows user to configure app tile text and background color , Starting new build with ability to change the color of the app tile logo
