### ISSUE TITLE
app settings synchronization across devices First Implementation

### ISSUE THREAD

**Issue by IsaacMorris1980** [colinkiama/UWP-App-Launcher#50]
Allow for settings to be synced from one windows device  to another

would this be a handy feature to add?

**Comment by mediaexplorer74** [comment]
App settings synchronization across devices is good idea :) Maybe, OneDrive's special folder could help... ;)

**Comment by IsaacMorris1980** [comment]
@mediaexplorer74  That was what i was thinking

**Comment by mediaexplorer74** [comment]
> @mediaexplorer74 That was what i was thinking

Great. Did you planned to repair (update) your great appLauncher? Today I noticed some activity on your IsaacMorris1980/appLauncher repo =) People interested in your project, really

Cheers up,
m.e.

**Comment by IsaacMorris1980** [comment]
@mediaexplorer74  i have released multiple versions since this enhancement ticket was entered current version is 2.1.14.0 , should have a new build with a few formatting fixes 2.1.15.0 

Next build after should either have this ticket or #9

**Comment by IsaacMorris1980** [comment]
@mediaexplorer74   it looks like #9  will be in the next build as i can not yet seem to get tokens required for this one to use onedrive special folder.  Still working on it though.

**Comment by IsaacMorris1980** [comment]
Starting on this 

Initial implementation will sync over same wifi

Second round of implementation will sync even if the devices are not on the same network(will create a ticket for this)

**Comment by IsaacMorris1980** [comment]
@mediaexplorer74   i might have a build with this implemented needed to be tested soon would you be able?   I dont have a windows computer with hyper-v ability so it will not run an emulator to have 2 different apps running on same wifi network

**Comment by IsaacMorris1980** [comment]
i will also try running windows 10 in a vm
