### ISSUE TITLE
Shelve project?

### ISSUE THREAD

**Issue by IsaacMorris1980** [colinkiama/UWP-App-Launcher#54]
With little feedback when questions were asked i am thinking about archiving the project after redesign and adding accessiblity to application.

**Comment by FireCubeStudios** [comment]
does this apply for non mobile as well

**Comment by IsaacMorris1980** [comment]
@FireCubeStudios   No as windows 10 devices continue to get support with each new update.  i will be closing the broad gap of supported sdk on non mobile.  Windows phones are no longer created and by the time i add accessibility to the project will no longer be supported by Microsoft so i am wondering if it should be continually supported by me or not

**Comment by gerardoriveradoesstuff** [comment]
hello, I absolutely love this app, please dont shelve this project. I use it on my x3 and 950, please continue to work on this! Thank you!

**Comment by IsaacMorris1980** [comment]
@gerardoriveradoesstuff   the only reason i am considering shelving is i have asked questions in the past about what people would like to see in the application(you know wanting to make it more what the users wanted)  and all i heard were crickets which i heard loud and clear as no one currently uses this so it did not need to be actively supported.  I have no problem supporting it and making it better adding features if i knew or heard back from people who use it

**Comment by gerardoriveradoesstuff** [comment]
@IsaacMorris1980 personally I would love to see folders, removing apps from start screen and being able to move the apps. Also it would be better if I open the apps list my keyboard won't automatically open up on mobile.

**Comment by IsaacMorris1980** [comment]
@gerardoriveradoesstuff   There is a build where you can move apps around and they persist between launches(https://github.com/IsaacMorris1980/UWP-App-Launcher-Mobile/releases/tag/V1.3.8-beta).  Folders are in the works.  Remove apps from start screen?  not sure what you mean here other then uninstalling them from the system .   Finally the keyboard issue i will create a bug and work on it.

**Comment by gerardoriveradoesstuff** [comment]
@IsaacMorris1980 this version doesn't seem to start on my elite x3

**Comment by IsaacMorris1980** [comment]
@gerardoriveradoesstuff   does give you any errors?

i also have to fix a color and opacity issue with that build

Can you tell me which version of windows 10 that is running?

**Comment by gerardoriveradoesstuff** [comment]
@IsaacMorris1980 It doesn't give any error, it takes a while to load, then the rocket does its flying animation and then it crashes.

**Comment by IsaacMorris1980** [comment]
@gerardoriveradoesstuff  is your device an x86 ; an x64 or a arm|arm64 device?  i have a new build with crash reporting build in

Never mind new build has issues as well sorry :(

**Comment by IsaacMorris1980** [comment]
Closing this not shelving product
