### ISSUE TITLE
Windows Search opens some times

### ISSUE THREAD

**Issue by lebao3105** [colinkiama/UWP-App-Launcher#61]
I'm using Lumia 640 XL with Windows 10 mobile build 15254 (1709). While I switching between pages on the launcher, sometimes Windows Search automatically opens although I'm not touched the navigation bar icon.

**Comment by IsaacMorris1980** [comment]
@lebao3105  which build of the app

**Comment by lebao3105** [comment]
It's 1.2.5.0

**Comment by IsaacMorris1980** [comment]
thank you looking into it

**Comment by IsaacMorris1980** [comment]
@lebao3105   Released version 2.0.11.0  as it changes the way the app navigates it might have fix this problem keeping this ticket open pending verification

**Comment by lebao3105** [comment]
I've tested it, and the problem is fixed! Thanks for your work

**Comment by IsaacMorris1980** [comment]
Thank you for reporting the issue
